# Generated by Django 4.1.5 on 2023-02-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_id', models.CharField(blank=True, max_length=5, null=True)),
                ('info_name', models.CharField(max_length=100)),
                ('info_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('info_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school_address', models.CharField(blank=True, max_length=100, null=True)),
                ('school_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('school_email', models.CharField(blank=True, max_length=100, null=True)),
                ('school_website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.IntegerField(default=0)),
                ('member_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.info')),
                ('member_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
        migrations.CreateModel(
            name='HeadMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headmaster_name', models.CharField(max_length=100)),
                ('headmaster_school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=100)),
                ('class_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
    ]
