# Generated by Django 4.1.5 on 2023-01-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=10)),
                ('school_address', models.CharField(max_length=100)),
                ('school_email', models.CharField(max_length=100)),
                ('school_website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=10)),
                ('student_email', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_phone', models.CharField(max_length=10)),
                ('teacher_email', models.CharField(default='teacher@gmail.com', max_length=100)),
                ('teacher_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
        migrations.CreateModel(
            name='HeadMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headmaster_name', models.CharField(max_length=100)),
                ('headmaster_school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
    ]
