# Generated by Django 4.1.5 on 2023-01-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_phone', models.CharField(max_length=10)),
                ('school_address', models.CharField(max_length=100)),
                ('school_email', models.CharField(max_length=100)),
                ('school_website', models.CharField(max_length=100)),
            ],
        ),
    ]
