# Generated by Django 4.1.5 on 2023-01-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='zipcode',
            field=models.CharField(default='NULL', max_length=5),
        ),
    ]
