# Generated by Django 4.1.5 on 2023-01-18 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.CharField(blank=True, default='teacher@gmail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school'),
        ),
    ]
