# Generated by Django 4.1.5 on 2023-01-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0002_school_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='zipcode',
        ),
    ]
