# Generated by Django 4.1.5 on 2023-01-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=10)),
                ('stu_fname', models.CharField(max_length=20)),
                ('stu_lname', models.CharField(max_length=20)),
                ('stu_phone', models.CharField(max_length=10)),
                ('stu_email', models.CharField(max_length=100)),
            ],
        ),
    ]
