# Generated by Django 4.1.5 on 2023-01-11 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0003_remove_school_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headmaster_name', models.CharField(max_length=100)),
                ('headmaster_school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
    ]
