# Generated by Django 4.1.5 on 2023-01-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0003_stu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='stu_sc',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
