# Generated by Django 4.1.5 on 2023-01-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0004_stu_stu_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='stu_sc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school'),
        ),
    ]
