# Generated by Django 4.1.5 on 2023-01-11 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0004_headmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Staff',
            fields=[
                ('staff_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_phone', models.CharField(max_length=10)),
                ('staff_email', models.CharField(max_length=100)),
                ('staff_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
    ]
