# Generated by Django 4.1.5 on 2023-01-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0005_remove_member_member_class_member_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
