# Generated by Django 4.1.5 on 2023-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0005_contact_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_Staff',
        ),
    ]
