# Generated by Django 4.1.5 on 2023-01-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0005_alter_stu_stu_sc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.teacher')),
            ],
        ),
    ]
