# Generated by Django 4.1.5 on 2023-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0006_teacher_delete_contact_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_id',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
