# Generated by Django 4.1.5 on 2023-01-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0006_alter_school_school_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_role',
            field=models.IntegerField(default=0),
        ),
    ]
