# Generated by Django 4.1.5 on 2023-01-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0007_school_school_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='school',
            name='school_id',
            field=models.CharField(max_length=5),
        ),
    ]
