# Generated by Django 4.1.5 on 2023-01-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexnetix', '0008_delete_teacher_alter_school_school_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_phone', models.CharField(max_length=10)),
                ('teacher_email', models.CharField(default='teacher@gmail.com', max_length=100)),
                ('teacher_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lexnetix.school')),
            ],
        ),
    ]
